name: Check for README

on: [push, pull_request]

jobs:
  check_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if README.md exists
        run: |
          if [ -f "README.md" ]; then
            echo "✅ README.md found."
          else
            echo "❌ README.md is missing!"
            exit 1
          fi